create table public.turno (
  id_turno bigint generated by default as identity not null,
  id_paciente bigint not null,
  id_canal bigint null,
  id_sede bigint null,
  id_estado bigint null,
  id_profesional bigint null,
  fecha timestamp with time zone null,
  constraint Turno_pkey primary key (id_turno),
  constraint Turno_id_paciente_fkey foreign KEY (id_paciente) references paciente (id_paciente),
  constraint turno_id_canal_fkey foreign KEY (id_canal) references canal_reserva (id_canal),
  constraint turno_id_estado_fkey foreign KEY (id_estado) references estado (id_estado),
  constraint turno_id_profesional_fkey foreign KEY (id_profesional) references profesional (id_profesional),
  constraint turno_id_sede_fkey foreign KEY (id_sede) references sede (id_sede)
) TABLESPACE pg_default;

create table public.paciente (
  id_paciente bigint generated by default as identity not null,
  id_cobertura_medica bigint not null,
  id_direccion bigint null,
  id_dn bigint null,
  nombre character varying null,
  apellido character varying null,
  numero_dn bigint null,
  id_genero bigint null,
  constraint Paciente_pkey primary key (id_paciente),
  constraint Paciente_id_cobertura_medica_fkey foreign KEY (id_cobertura_medica) references cobertura_medica (id_cobertura_medica),
  constraint Paciente_id_direccion_fkey foreign KEY (id_direccion) references direccion (id_direccion),
  constraint Paciente_id_dn_fkey foreign KEY (id_dn) references tipo_documento (id_dn),
  constraint Paciente_id_genero_fkey foreign KEY (id_genero) references genero (id_genero)
) TABLESPACE pg_default;

create table public.atencion (
  id_atencion bigint generated by default as identity not null,
  id_turno bigint not null,
  fecha_inicio_consulta timestamp with time zone null,
  fecha_fin_consulta timestamp with time zone null,
  fue_sobreturno boolean null,
  constraint atencion_pkey primary key (id_atencion),
  constraint atencion_id_turno_key unique (id_turno)
) TABLESPACE pg_default;

create table public.barrio (
  id_barrio bigint generated by default as identity not null,
  id_departamento bigint not null,
  nombre_barrio character varying null,
  constraint Barrio_pkey primary key (id_barrio),
  constraint Barrio_id_departamento_fkey foreign KEY (id_departamento) references departamento (id_departamento)
) TABLESPACE pg_default;

create table public.canal_reserva (
  id_canal bigint generated by default as identity not null,
  tipo_canal character varying not null,
  constraint canal_reserva_pkey primary key (id_canal)
) TABLESPACE pg_default;

create table public.cobertura_medica (
  id_cobertura_medica bigint generated by default as identity not null,
  nombre character varying not null,
  constraint Cobertura medica_pkey primary key (id_cobertura_medica)
) TABLESPACE pg_default;

create table public.departamento (
  id_departamento bigint generated by default as identity not null,
  id_provincia bigint not null,
  departamento character varying null,
  constraint Departamento_pkey primary key (id_departamento),
  constraint Departamento_id_provincia_fkey foreign KEY (id_provincia) references provincia (id_provincia)
) TABLESPACE pg_default;

create table public.direccion (
  id_direccion bigint generated by default as identity not null,
  id_barrio bigint not null,
  calle character varying null,
  numero bigint null,
  aclaracion text null,
  constraint Direccion_pkey primary key (id_direccion),
  constraint Direccion_id_barrio_fkey foreign KEY (id_barrio) references barrio (id_barrio)
) TABLESPACE pg_default;

create table public.especialidad (
  id_especialidad bigint generated by default as identity not null,
  especialidad bigint not null,
  constraint especialidad_pkey primary key (id_especialidad)
) TABLESPACE pg_default;

create table public.estado (
  id_estado bigint generated by default as identity not null,
  estado character varying not null,
  constraint estado_pkey primary key (id_estado)
) TABLESPACE pg_default;

create table public.genero (
  id_genero bigint generated by default as identity not null,
  genero character varying not null,
  constraint Genero_pkey primary key (id_genero)
) TABLESPACE pg_default;

create table public.profesional (
  id_profesional bigint generated by default as identity not null,
  nombre character varying not null,
  apellido character varying null,
  constraint profesional_pkey primary key (id_profesional)
) TABLESPACE pg_default;

create table public.profesional_especialidad (
  id_profesional bigint generated by default as identity not null,
  id_especialidad bigint not null,
  constraint profesional_especialidad_pkey primary key (id_profesional, id_especialidad),
  constraint profesional_especialidad_id_especialidad_fkey foreign KEY (id_especialidad) references especialidad (id_especialidad),
  constraint profesional_especialidad_id_profesional_fkey foreign KEY (id_profesional) references profesional (id_profesional)
) TABLESPACE pg_default;

create table public.provincia (
  id_provincia bigint generated by default as identity not null,
  provincia character varying not null,
  constraint Provincia_pkey primary key (id_provincia)
) TABLESPACE pg_default;

create table public.sede (
  id_sede bigint generated by default as identity not null,
  id_direccion bigint not null,
  nombre character varying null,
  constraint sede_pkey primary key (id_sede),
  constraint sede_id_direccion_fkey foreign KEY (id_direccion) references direccion (id_direccion)
) TABLESPACE pg_default;

create table public.tipo_documento (
  id_dn bigint generated by default as identity not null,
  tipo_dn character varying not null,
  constraint Tipo_Documento_pkey primary key (id_dn)
) TABLESPACE pg_default;